### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Kunal2341** [adhikary97/girlfriend_text#4]
python main.py
'osascript' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Sciencewolf** [comment]
> python main.py
> 'osascript' is not recognized as an internal or external command,
> operable program or batch file.

same but i clear 'osascript' and its work but i dont reseive a message((

**Comment by Sky-Hong** [comment]
Same. 
python main.py
'osascript' is not recognized as an internal or external command,
operable program or batch file.

**Comment by adhikary97** [comment]
osascript is apple's command to run applescript. if you don't have a mac and want to use sms checkout my other repo motivation text that uses email to send sms
